name: untitled
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: antonio <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  rpc: "^0.5.7+1"
  http: '>=0.11.1 <0.12.0'

dev_dependencies:
  test: ^0.12.0
